data_parser/urls.py
from django.contrib.auth import views as auth_views
from django.conf.urls.static import static

from django.urls import path
from django.conf import settings

from .forms import UserLoginForm
from .views import *

app_name = 'data_parser'


urlpatterns = [
    path('login/',
         auth_views.LoginView.as_view(template_name="registration/login.html", authentication_form=UserLoginForm),
         name='login'),
    path('profile/', profile_view, name="profile"),
    path('register', RegisterView.as_view(), name="register"),
    path('password_reset/', WebPasswordResetView.as_view(), name="password_reset"),
    path('password_reset/done/', WebPasswordResetDoneView.as_view(), name="password_reset_done"),
    path('reset/<uidb64>/<token>/',
         WebPasswordResetConfirmView.as_view(),
         name='password_reset_confirm'),
    path('reset/done/',
         WebPasswordResetCompleteView.as_view(),
         name='password_reset_complete'),
    path('password_change/', WebPasswordChangeView.as_view(), name="password_change"),
    path('password_change/done/', WebPasswordChangeDoneView.as_view(), name="password_change_done"),
    path('view_links/', urls_view, name='view_links'),
    path('add_link/', add_link, name='add_link'),
    path('edit_link/<int:link_id>/', edit_link, name='edit_link'),
    path('view_link/<int:link_id>/', view_link, name='view_link'),
    path('delete_all_links/', delete_all_links, name='delete_all_links'),
    path('delete_selected_links/', delete_selected_links, name='delete_selected_links'),
    path('url_parser/', url_parser, name='url_parser'),
    path('url_parser/<path:url>/', url_parser_by_link, name='url_parser'),
    path('view_collections/', view_collections, name='view_collections'),
    path('view_collections/<str:collection_name>/', view_collection, name='view_collection'),
    path('delete_all_collections/', delete_all_collections, name='delete_all_collections'),
    path('delete_selected_collections/', delete_selected_collections, name='delete_selected_collections'),
    path('edit_collection/<int:collection_id>/', edit_collection, name='edit_collection'),
    path('view_top_users/', view_top_users, name='view_top_users'),
    path('', lambda request: redirect('profile/', permanent=True)),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

django_test_task/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from drf_yasg import openapi
from drf_yasg.views import get_schema_view as swagger_get_schema_view

schema_view = swagger_get_schema_view(
    openapi.Info(
        title="My API",
        default_version='1.0.0',
        description="URL parser API description",
        contact=openapi.Contact(email="sevastsyanmatusevich@proton.me"),
    ),
    patterns=[path('', include('data_parser.urls')), ],
    public=True,
)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('data_parser.urls')),
    path('swagger/schema/', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger'),
    path('redoc/', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

data_parser/forms.py
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm, UsernameField
from django.contrib.auth.models import User
from django import forms
from .models import Link, Collection


class RegisterForm(UserCreationForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['password1'].label = 'password 1 label'
        self.fields['password2'].label = 'password 2 label'

    class Meta(UserCreationForm.Meta):
        model = User
        fields = ['username', 'email', 'password1', 'password2']
        labels = {
            'username': 'Пользователь',
            'email': 'Почта',
            'password1': 'Пароль',
            'password2': 'Подтверждение пароля',
        }
        help_texts = {
            'password1': 'Пароль',
            'password2': 'Подтверждение пароля',
        }
        widgets = {
            'username': forms.TextInput(attrs={'class': 'form-control'}),
            'email': forms.EmailInput(attrs={'class': 'form-control'}),
            'password1': forms.PasswordInput(attrs={'class': 'form-control'}),
            'password2': forms.PasswordInput(attrs={'class': 'form-control'}),
        }

    def __init__(self, *args, **kwargs):
        super(RegisterForm, self).__init__(*args, **kwargs)
        self.fields['password1'].widget = forms.PasswordInput(attrs={'class': 'form-control'})
        self.fields['password2'].widget = forms.PasswordInput(attrs={'class': 'form-control'})


class LinkForm(forms.ModelForm):
    class Meta:
        model = Link
        fields = ['title', 'description', 'url', 'image', 'collection']
        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control'}),
            'description': forms.TextInput(attrs={'class': 'form-control'}),
            'url': forms.TextInput(attrs={'class': 'form-control'}),
            'image': forms.TextInput(attrs={'class': 'form-control'}),
            'collection': forms.Select(attrs={'class': 'form-control'}),
        }


class ParseUrlForm(forms.Form):
    url = forms.CharField(label="Введите URL (либо URL'ы)", max_length=20000, widget=forms.Textarea(attrs={'class': 'form-control', 'placeholder': 'Через запятую: https://stackoverflow.com, https://www.youtube.com/,.....'}))


class CollectionForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(CollectionForm, self).__init__(*args, **kwargs)
        self.fields['name'].disabled = True

    class Meta:
        model = Collection
        fields = ['name', 'description']
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control'}),
            'description': forms.TextInput(attrs={'class': 'form-control'}),
        }


class UserLoginForm(AuthenticationForm):
    def __init__(self, *args, **kwargs):
        super(UserLoginForm, self).__init__(*args, **kwargs)

    fields = ['username', 'password']

    widgets = {
        'username': forms.TextInput(attrs={'class': 'form-control'}),
        'password': forms.TextInput(attrs={'class': 'form-control'}),
    }

    username = UsernameField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control'}))

data_parser/views.py
import json

from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.contrib.auth.views import PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, \
    PasswordResetCompleteView, PasswordChangeView, PasswordChangeDoneView
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse_lazy, reverse
from django.views.generic import FormView
from data_parser.models import Link, Collection
from django.http import Http404, JsonResponse
from django.db import connection
from rest_framework.decorators import api_view
from rest_framework.response import Response
from drf_yasg.utils import swagger_auto_schema
from .forms import RegisterForm, LinkForm, ParseUrlForm, CollectionForm
from parser import UrlParser
import asyncio


@api_view(['GET'])
@swagger_auto_schema(
    operation_description="Returns a list of all users.",
    responses={200: 'OK'})


@login_required
def profile_view(request):
    current_user = request.user

    all_collections = Collection.objects.all()

    collections_with_links = []
    all_links_count = Link.objects.filter(user=current_user).count()

    for collection in all_collections:
        links_count = Link.objects.filter(user=current_user, collection_id=collection.id).count()
        if links_count > 0:
            collections_with_links.append({
                'collection': collection,
            })

    context = {
        'collections_count': len(collections_with_links),
        'links_count': all_links_count
    }

    return render(request, context=context, template_name='profile.html')


class RegisterView(FormView):
    model = User
    form_class = RegisterForm
    template_name = 'registration/register.html'
    success_url = reverse_lazy('data_parser:profile')

    @swagger_auto_schema(
        operation_description="Process registration form.",
        responses={200: 'OK'}
    )

    def form_valid(self, form):
        form.save()
        return super().form_valid(form)


class WebPasswordResetView(PasswordResetView):
    template_name = 'registration/password_reset.html'
    email_template_name = 'registration/password_reset_email_.html'
    html_email_template_name = 'registration/password_reset_email_.html'
    success_url = reverse_lazy('data_parser:password_reset_done')


class WebPasswordResetConfirmView(PasswordResetConfirmView):
    template_name = 'registration/password_reset_confirm_.html'
    success_url = reverse_lazy('data_parser:password_reset_complete')


class WebPasswordResetCompleteView(PasswordResetCompleteView):
    template_name = 'registration/password_reset_complete_.html'


class WebPasswordResetDoneView(PasswordResetDoneView):
    template_name = 'registration/password_reset_done_.html'


class WebPasswordChangeView(PasswordChangeView):
    template_name = 'registration/password_change_.html'
    success_url = reverse_lazy('data_parser:password_change_done')


class WebPasswordChangeDoneView(PasswordChangeDoneView):
    template_name = 'registration/password_change_done_.html'

@api_view(['GET'])
@swagger_auto_schema(
    operation_description="View user's URLs.",
    responses={200: 'OK'}
)

@login_required
def urls_view(request):
    current_user = request.user

    links = Link.objects.filter(user=current_user)

    context = {
        'links': links
    }

    return render(request, 'view_urls.html', context)

@api_view(['GET', 'POST'])
@swagger_auto_schema(
    operation_description="Edit link details.",
    responses={200: 'OK'}
)

@login_required
def edit_link(request, link_id):
    link = get_object_or_404(Link, id=link_id)
    if request.method == 'POST':
        form = LinkForm(request.POST, instance=link)
        if form.is_valid():
            form.save()
            return redirect('data_parser:view_links')
    else:
        form = LinkForm(instance=link)
    return render(request, 'edit_link.html', {'form': form})


@api_view(['GET'])
@swagger_auto_schema(
    operation_description="View details of a specific link.",
    responses={200: 'OK'}
)
@login_required
def view_link(request, link_id):
    link = get_object_or_404(Link, id=link_id)
    return render(request, 'view_link.html', {'link': link})

@api_view(['GET', 'POST'])
@swagger_auto_schema(
    operation_description="Add a new link.",
    responses={200: 'OK'}
)

@login_required
def add_link(request):
    if request.method == 'POST':
        form = LinkForm(request.POST)
        if form.is_valid():
            link = form.save(commit=False)
            link.user = request.user
            link.save()
            return redirect('data_parser:view_links')
    else:
        form = LinkForm()
    return render(request, 'add_link.html', {'form': form})


@api_view(['GET'])
@swagger_auto_schema(
    operation_description="Delete all links.",
    responses={200: 'OK'}
)
@login_required
def delete_all_links(request):
    if Link.objects.filter(user=request.user).exists():
        Link.objects.filter(user=request.user).delete()
    return redirect(reverse_lazy('data_parser:view_links'))


@api_view(['GET'])
@swagger_auto_schema(
    operation_description="Delete selected links.",
    responses={200: 'OK'}
)
@login_required
def delete_selected_links(request):
    if request.method == 'GET':
        selected_ids = request.GET.getlist('ids')
        selected_ids = [int(id) for ids in selected_ids for id in ids.split(',') if id.isdigit()]
        if selected_ids:
            if Link.objects.filter(user=request.user, id__in=selected_ids).exists():
                Link.objects.filter(user=request.user, id__in=selected_ids).delete()
        return redirect(reverse_lazy('data_parser:view_links'))
    return redirect(reverse_lazy('data_parser:view_links'))


@api_view(['POST'])
@swagger_auto_schema(
    operation_description="Parse URLs and save links.",
    request_body=LinkForm,
    responses={200: 'OK'})

@login_required
def url_parser(request):
    if request.method == 'POST':
        form = ParseUrlForm(request.POST)
        if form.is_valid():
            urls = form.cleaned_data['url']
            asyncio.run(parse_info_async(urls, request.user))
            return redirect(reverse_lazy('data_parser:view_links'))
    else:
        form = ParseUrlForm()
    return render(request, 'urls_parser.html', {'form': form})


@api_view(['GET'])
@swagger_auto_schema(
    operation_description="Parse URLs and save links.",
    responses={200: 'OK'}
)
@login_required
def url_parser_by_link(request, url):
    if request.method == 'GET':
        result = asyncio.run(parse_info_async(url, request.user, get_=True))
        return JsonResponse(json.loads(result))


async def parse_info_async(urls, user, get_=None):
    parse_info = UrlParser()
    result = await parse_info.parse_info(urls, user, get_)
    return result

@api_view(['GET'])
@swagger_auto_schema(
    operation_description="View user collections.",
    responses={200: 'OK'}
)

@login_required
def view_collections(request):
    current_user = request.user

    all_collections = Collection.objects.filter(user=current_user)

    collections_with_links = []
    for collection in all_collections:
        links_count = Link.objects.filter(user=current_user, collection_id=collection.id).count()
        if links_count > 0:
            collections_with_links.append({
                'collection': collection,
                'links_count': links_count
            })

    context = {
        'collections_with_links': collections_with_links
    }

    return render(request, 'view_collections.html', context)


@api_view(['GET'])
@swagger_auto_schema(
    operation_description="View collection details.",
    responses={200: 'OK'}
)

@login_required
def view_collection(request, collection_name):
    current_user = request.user

    collection = get_object_or_404(Collection, name=collection_name, user=current_user)
    links = Link.objects.filter(user=current_user, collection=collection)

    if not links:
        raise Http404("No links found in this collection.")

    context = {
        'collection': collection,
        'links': links
    }

    return render(request, 'view_collection.html', context)

@api_view(['POST'])
@swagger_auto_schema(
    operation_description="Delete all collections.",
    responses={200: 'OK'}
)
@login_required
def delete_all_collections(request):
    Collection.objects.filter(user=request.user).delete()
    return redirect(reverse_lazy('data_parser:view_collections'))


@api_view(['GET', 'POST'])
@swagger_auto_schema(
    operation_description="Delete selected collections.",
    responses={200: 'OK'}
)
@login_required
def delete_selected_collections(request):
    if request.method == 'GET':
        selected_ids = request.GET.getlist('ids')
        selected_ids = [int(id) for id in selected_ids if id.isdigit()]
        Collection.objects.filter(id__in=selected_ids, user=request.user).delete()
    return redirect(reverse_lazy('data_parser:view_collections'))

@api_view(['GET', 'POST'])
@swagger_auto_schema(
    operation_description="Edit collection details.",
    responses={200: 'OK'}
)

@login_required
def edit_collection(request, collection_id):
    collection = get_object_or_404(Collection, id=collection_id, user=request.user)
    if request.method == 'POST':
        form = CollectionForm(request.POST, instance=collection)
        if form.is_valid():
            form.save()
            return redirect('data_parser:view_collections')
    else:
        form = CollectionForm(instance=collection)
    return render(request, 'edit_collection.html', {'form': form})

@api_view(['GET'])
@swagger_auto_schema(
    operation_description="View top users.",
    responses={200: 'OK'}
)

@login_required
def view_top_users(request):
    with connection.cursor() as cursor:
        cursor.execute('SELECT DISTINCT id, name FROM data_parser_collection;')
        categories = cursor.fetchall()

        count_expressions = []

data_parser/templates/add_link.html
{% extends 'base.html' %}
{% block title %}Добавить ссылку{% endblock %}
{% block content %}
<div class="container">
    <a href="{% url 'data_parser:view_links' %}" class="btn btn-info mt-3" style="color: white;">Вернуться ко всем линкам</a>
    <h2 class="mt-4 mb-3">Добавить ссылку</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">Добавить ссылку</button>
    </form>
</div>
{% endblock %}

data_parser/templates/edit_collection.html
{% extends 'base.html' %}
{% block title %}Редактировать коллекцию{% endblock %}
{% block content %}
<div class="container">
    <a href="{% url 'data_parser:view_collections' %}" class="btn btn-info mt-3" style="color: white;">Вернуться ко всем коллекциям</a>
    <h2 class="mt-4 mb-3">Редактировать  коллекцию</h2>
    <form method="post">
        {% csrf_token %}
           {{ form.as_p }}
        <button type="submit" class="btn btn-primary">Сохранить изменения</button>
    </form>
</div>


{% endblock %}

data_parser/templates/profile.html
{% extends 'base.html' %}
{% block title %}Профиль | {{user.username}} {% endblock %}
{% block content %}
<section class="vh-100" style="background-color: #9de2ff;">
    <div class="container py-5 h-100">
        <div class="row d-flex justify-content-center align-items-center h-100">
            <div class="col col-md-9 col-lg-7 col-xl-5">
                <div class="card" style="border-radius: 15px;">
                    <div class="card-body p-4">
                        <div class="d-flex text-black">
                            <div class="flex-grow-1 ms-3">
                                <h5 class="mb-1">{{ user.username }}</h5>
                                <p class="mb-2 pb-1" style="color: #2b2a2a;">{{ user.email }}</p>
                                <div class="d-flex justify-content-start rounded-3 p-2 mb-2"
                                     style="background-color: #efefef;">
                                    <div>
                                        <p class="small text-muted mb-1">Количество ссылок</p>
                                        <p class="mb-0"><a class="text-decoration-none"
                                                           href="{% url 'data_parser:view_links' %}">{{ links_count }}</a></p>
                                    </div>
                                    <div class="px-3">
                                        <p class="small text-muted mb-1">Количество коллекций</p>
                                        <p class="mb-0"><a class="text-decoration-none"
                                                           href="{% url 'data_parser:view_collections' %}">{{ collections_count }}</a></p>
                                    </div>
                                </div>
                                <div class="d-flex pt-1">
                                    <form method="post"
                                          action="{% url 'data_parser:password_change' %}?next=/parser/profile/">
                                        {% csrf_token %}
                                        <button type="submit" data-mdb-button-init data-mdb-ripple-init
                                                class="btn btn-outline-primary me-1 flex-grow-1">Сменить пароль
                                        </button>
                                    </form>
                                    <form method="post" action="{% url 'logout' %}?next=/profile/">
                                        {% csrf_token %}
                                        <button type="submit" data-mdb-button-init data-mdb-ripple-init
                                                class="btn btn-primary flex-grow-1">Выйти из аккаунта
                                        </button>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock %}

data_parser/templates/view_collection.html
{% extends 'base.html' %}
{% block title %}Коллекция - {{collection}} {% endblock %}
{% block content %}
<div class="container">
    <a href="{% url 'data_parser:view_collections' %}" class="btn btn-info mt-3" style="color: white;">Вернуться ко всем коллекциям</a>
    <h2 class="mt-4 mb-3">Ссылки пользователя {{ user.username }} в коллекции {{ collection }}</h2>
    <button type="button" class="btn btn-danger mb-3" id="delete-selected">Удалить выбранные</button>
    <button type="button" class="btn btn-danger mb-3" id="delete-all">Удалить все</button>
    <div class="table-responsive overflow-auto" style="max-height: 1000px;">
        <table id="table" class="table table-bordered" style="cursor: pointer;">
            <thead>
            <tr>
                <th>Выбрать</th>
                <th>Заголовок</th>
                <th>Описание</th>
                <th>URL</th>
                <th>Изображение</th>
                <th>Дата добавления</th>
                <th>Дата обновления</th>
                <th>Действия</th>
            </tr>
            </thead>
            <tbody>
            {% for link in links %}
            <tr>
                <td><input type="checkbox" class="link-checkbox" value="{{ link.id }}"></td>
                <td>{{ link.title }}</td>
                <td>{{ link.description }}</td>
                <td><a href="{{ link.url }}" target="_blank">{{ link.url }}</a></td>
                <td>
                    {% if link.image %}
                    <img src="{{ link.image }}" style="max-width: 100px;">
                    {% else %}
                    No image
                    {% endif %}
                </td>
                <td>{{ link.created_at }}</td>
                <td>{{ link.updated_at }}</td>
                <td>
                    <a href="{% url 'data_parser:edit_link' link.id %}" class="link-warning">Редактировать</a>
                    <a href="{% url 'data_parser:view_link' link.id %}" class="link-info">Просмотреть</a>
                </td>
            </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
</div>

<script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>
<script>
        $(document).ready(function () {
           $('#table tr').click(function (event) {
               if (event.target.type !== 'checkbox') {
                   $(':checkbox', this).trigger('click');
               }
           });
       });
</script>

<script>
    document.addEventListener("DOMContentLoaded", function () {
        const deleteSelectedButton = document.getElementById('delete-selected');
        const deleteAllButton = document.getElementById('delete-all');
        const checkboxes = document.querySelectorAll('.link-checkbox');

        // Обработчик для кнопки удаления выбранных ссылок
        deleteSelectedButton.addEventListener('click', function () {
            const selectedIds = [];
            checkboxes.forEach(checkbox => {
                if (checkbox.checked) {
                    selectedIds.push(checkbox.value);
                }
            });
            // Перенаправляем на страницу удаления ссылок с выбранными ID
            window.location.href = '{% url "data_parser:delete_selected_links" %}?ids=' + selectedIds.join(',');
        });

        // Обработчик для кнопки удаления всех ссылок
        deleteAllButton.addEventListener('click', function () {
            // Перенаправляем на страницу удаления всех ссылок
            window.location.href = '{% url "data_parser:delete_all_links" %}';
        });
    });

</script>
{% endblock %}

data_parser/templates/view_collections.html
{% extends 'base.html' %}
{% block title %}Коллекции | {{user.username}} {% endblock %}
{% block content %}
<div class="container">
    <a href="{% url 'data_parser:view_links' %}" class="btn btn-info mt-3" style="color: white;">Вернуться ко всем
        линкам</a>
    <h2 class="mt-4 mb-3">Коллекции пользователя {{ user.username }}</h2>
    <button type="button" class="btn btn-danger mb-3" id="delete-selected">Удалить выбранные коллекции и ссылки</button>
    <button type="button" class="btn btn-danger mb-3" id="delete-all">Удалить все коллекции и ссылки</button>
    <div class="table-responsive overflow-auto" style="max-height: 1000px;">
        <table id="table" class="table table-bordered" style="cursor: pointer;">
            <thead>
            <tr>
                <th>Выбрать</th>
                <th>Название коллекции</th>
                <th>Описание</th>
                <th>Количество ссылок</th>
                <th>Действия</th>
            </tr>
            </thead>
            <tbody>
            {% for item in collections_with_links %}
            <tr>
                <td><input type="checkbox" class="link-checkbox" value="{{ item.collection.id }}"></td>
                <td><a href="{% url 'data_parser:view_collections' %}{{ item.collection.name }}/">{{ item.collection.name }}</a></td>
                <td>{{ item.collection.description }}</td>
                <td>{{ item.links_count }}</td>
                <td>
                    <a href="{% url 'data_parser:edit_collection' item.collection.id %}" class="link-warning">Редактировать</a><br>
                    <a href="{% url 'data_parser:view_collections' %}{{ item.collection.name }}/" class="link-info">Просмотреть</a>
                </td>
            </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
</div>

<script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>
<script>
$(document).ready(function () {
   $('#table tr').click(function (event) {
       if (event.target.type !== 'checkbox') {
           $(':checkbox', this).trigger('click');
       }
   });
});

</script>

<script>
document.addEventListener("DOMContentLoaded", function () {
    const deleteSelectedButton = document.getElementById('delete-selected');
    const deleteAllButton = document.getElementById('delete-all');
    const checkboxes = document.querySelectorAll('.link-checkbox');

    // Обработчик для кнопки удаления выбранных коллекций
    deleteSelectedButton.addEventListener('click', function () {
        const selectedIds = [];
        checkboxes.forEach(checkbox => {
            if (checkbox.checked) {
                selectedIds.push(checkbox.value);
            }
        });
        // Перенаправляем на страницу удаления коллекций с выбранными ID
        window.location.href = '{% url "data_parser:delete_selected_collections" %}?ids=' + selectedIds.join(',');
    });

    // Обработчик для кнопки удаления всех коллекций
    deleteAllButton.addEventListener('click', function () {
        // Перенаправляем на страницу удаления всех коллекций
        window.location.href = '{% url "data_parser:delete_all_collections" %}';
    });
});

</script>
{% endblock %}

data_parser/templates/view_urls.html
{% extends 'base.html' %}
{% block title %}Ссылки | {{user.username}} {% endblock %}
{% block content %}
<div class="container">
    <h2 class="mt-4 mb-3">Ссылки пользователя {{ user.username }}</h2>
    <a href="{% url 'data_parser:add_link' %}" class="btn btn-primary mb-3">Добавить ссылку вручную</a>
    <button type="button" class="btn btn-danger mb-3" id="delete-selected">Удалить выбранные</button>
    <button type="button" class="btn btn-danger mb-3" id="delete-all">Удалить все</button>
    <div class="table-responsive overflow-auto" style="max-height: 1000px;">
        <table id="table" class="table table-bordered" style="cursor: pointer;">
            <thead>
            <tr>
                <th>Выбрать</th>
                <th>Заголовок</th>
                <th>Описание</th>
                <th>URL</th>
                <th>Изображение</th>
                <th>Тип ссылки</th>
                <th>Дата добавления</th>
                <th>Дата обновления</th>
                <th>Действия</th>
            </tr>
            </thead>
            <tbody>
            {% for link in links %}
            <tr>
                <td><input type="checkbox" class="link-checkbox" value="{{ link.id }}"></td>
                <td>{{ link.title }}</td>
                <td>{{ link.description }}</td>
                <td><a href="{{ link.url }}" target="_blank">{{ link.url }}</a></td>
                <td>
                    {% if link.image %}
                    <img src="{{ link.image }}" style="max-width: 100px;">
                    {% else %}
                    No image
                    {% endif %}
                </td>
                <td><a href="{% url 'data_parser:view_collections' %}{{ link.collection }}/">{{ link.collection }}</a></td>

                <td>{{ link.created_at }}</td>
                <td>{{ link.updated_at }}</td>
                <td>
                    <a href="{% url 'data_parser:edit_link' link.id %}" class="link-warning">Редактировать</a>
                    <a href="{% url 'data_parser:view_link' link.id %}" class="link-info">Просмотреть</a>
                </td>
            </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
</div>

<script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>
<script>
        $(document).ready(function () {
           $('#table tr').click(function (event) {
               if (event.target.type !== 'checkbox') {
                   $(':checkbox', this).trigger('click');
               }
           });
       });
</script>

<script>
    document.addEventListener("DOMContentLoaded", function () {
        const deleteSelectedButton = document.getElementById('delete-selected');
        const deleteAllButton = document.getElementById('delete-all');
        const checkboxes = document.querySelectorAll('.link-checkbox');

        // Обработчик для кнопки удаления выбранных ссылок
        deleteSelectedButton.addEventListener('click', function () {
            const selectedIds = [];
            checkboxes.forEach(checkbox => {
                if (checkbox.checked) {
                    selectedIds.push(checkbox.value);
                }
            });
            // Перенаправляем на страницу удаления ссылок с выбранными ID
            window.location.href = '{% url "data_parser:delete_selected_links" %}?ids=' + selectedIds.join(',');
        });

        // Обработчик для кнопки удаления всех ссылок
        deleteAllButton.addEventListener('click', function () {
            // Перенаправляем на страницу удаления всех ссылок
            window.location.href = '{% url "data_parser:delete_all_links" %}';
        });
    });

</script>
{% endblock %}